Vagrant.configure("2") do |config|

  ## 2 ubuntu VMs 
  (10..11).each do |i|
    config.vm.define "ubuntu#{i}" do | ubuntu |
      ubuntu.vm.box = "ubuntu/bionic64"
      ubuntu.vm.network "private_network", ip: "192.168.50.#{i}"
    end
  end 

  ## 2 centos VMs
  (20..21).each do |i|
    config.vm.define "centos#{i}" do | centos |
      centos.vm.box = "centos/8"
      centos.vm.network "private_network", ip: "192.168.50.#{i}"
    end
  end








  ## Performance options ##
  # tweak or remove these as you see fit:
  config.vm.box_check_update = false

  # provider (hypervisor in vagrant parlance):
    # docs: https://www.vagrantup.com/docs/providers/basic_usage.html#default-provider
    # vagrant will search for first configured provider, unless you use one of these overrides:
      # `--provider` CLI option
      # `VAGRANT_DEFAULT_PROVIDER` environment variable
    # VirtualBox is a great cross platform, free hypervisor 
      # I recommend using it 
      # If you change providers, make sure the boxes above have a build for said provider.
  config.vm.provider "virtualbox" do |v|

    # add vboxmanage customizations here:
    # https://www.vagrantup.com/docs/virtualbox/configuration.html
    # "convenience shortcuts for memory and CPU settings:" (per link above), tweak to your machine's capabilities to speed up VMs:
      v.memory = 8192
      v.cpus = 4

  end

end
 